config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  resources :projects do
    resources :tasks
  end

  devise_for :users

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  
  belongs_to :task
  has_many_attached :files
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, :description, presence: true
  
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: true

  belongs_to :project
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :task_id, files: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if user_signed_in?
    #   @projects = current_user.projects.all
    # end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    set_project
    @tasks = @project.tasks.order(created_at: "DESC")
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @comments = @task.comments.all
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:description, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_id, 'Choose task' %>
    <%= form.collection_select(:task_id, Task.all, :id, :description) %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :file, 'Attach files' %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Comments</h1>

<table>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Project: <%= @comment.task.project.title %></h3>
<h4>Task: <%= @comment.task.description %></h4>
<%= link_to 'Back to tasks', tasks_path %>
<p>
  <strong>Comment: </strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> | 
<%= link_to 'Delete', @comment, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/home/index.html.erb
<h1 class="font-weight-bold text-muted mb-4 mt-5 text-center border-bottom pb-4">Charge</h1>
<p class="text-muted w-50 mx-auto text-center">
  This is a simple tool that helps me control my task flow.
  I want to manage my tasks and projects more effectively.
</p>

<% if user_signed_in? %>
<div class="mt-5 text-center">
  <div>
    <%= link_to '<i class="fas fa-plus text-primary"></i>'.html_safe, new_project_path, class: 'border py-2 px-3 rounded text-muted' %>
  </div>
  <div class="mt-4">
    <%= link_to 'New Project', new_project_path, class: 'text-muted' %>
  </div>
  <div class="mt-5">
    <%= link_to 'Go to my projects<i class="fas fa-arrow-right ml-3"></i>'.html_safe, projects_path, class: 'alert alert-primary font-weight-bold' %>
  </div>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="py-4 d-flex justify-content-end">
<% if current_user %>
  <p class="mr-3 text-muted">Hello, <%= current_user.email %></p>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to 'New account?', new_user_registration_path, class: 'mr-2' %>
  <span class="mr-2">or</span>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <%= yield %>
    </div>

    <script
      src="https://kit.fontawesome.com/7290f27402.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center mt-4 border-bottom pb-4 mb-5">My <span class="text-muted">Projects</span></h1>

<div class="text-center">
  <div>
    <%= link_to '<i class="fas fa-plus text-primary"></i>'.html_safe, new_project_path, class: 'border py-2 px-3 rounded text-muted' %>
  </div>
  <div class="mt-4">
    <%= link_to 'New Project', new_project_path, class: 'text-muted' %>
  </div>
</div>

<div class="bg-light mt-4 mx-auto w-50 rounded py-4 px-5">
<% @projects.each do |project| %>
  <span class="d-block border-bottom py-3 pl-2">
  <i class="fas fa-arrow-circle-right mr-3 text-muted"></i>
  <%= link_to project.title, project, class: 'font-weight-bold' %>
  </span>
<% end %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '<i class="fas fa-arrow-left mr-3"></i>Back to projects'.html_safe, projects_path, class: 'text-muted' %>

<div class="row">
  <div class="col-lg-4">
    <div>
      <h1 class="my-5">
        Project: <br>
        <span class="text-muted">
          <%= @project.title %>
        </span>
      </h1>
      <p class="mb-5">
        <span class="font-weight-bold text-muted mb-3 d-block">
          About this project.
        </span>
        <span class="text-muted">
          <%= @project.description %>
        </span>
      </p>
      <%= link_to '<i class="fas fa-pencil-alt mr-2"></i>Edit'.html_safe, edit_project_path(@project), class: 'mr-4 font-weight-bold'%>
      <%= link_to '<i class="fas fa-trash mr-2"></i>Delete'.html_safe, @project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'font-weight-bold' %>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="bg-light py-4 px-5">
      <% if current_user %>
        <div>
          <h4 class="text-muted border-bottom py-4 mb-4 text-center">Tasks for this project</h4>
          
          <div class="mt-5 w-75 mx-auto">
            <% @tasks.each do |task| %>
              <div class="d-flex my-3">
                <%= form_tag('', method: '', class: 'mt-1') do %>
                  <%= check_box_tag(:complete) %>
                <% end %> 
                <span class="ml-2"><%= task.description %><span>
              </div>
            <% end %>
          </div>

          <div>
            <%= form_for([@project, @project.tasks.build]) do |form| %>
              <div class="field mb-4">
                <%= form.text_area :description, class: 'form-control', placeholder: 'Enter new task', style: 'height: 5.5em'%>
              </div>
              <div class="actions">
                <%= form.submit 'Add', class: 'btn btn-primary py-3 px-5 rounded-0' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-4">
      <%= link_to '<i class="fas fa-arrow-left mr-3"></i>Back to projects'.html_safe, projects_path, class: 'text-muted' %>
      <div class="field mt-5 pt-4">
        <%= form.label :project_id, 'Select a project', class: 'big-font font-weight-bold mb-3' %>
        <%= form.collection_select(:project_id, Project.all, :id, :title, {}, class: 'custom-select field-height') %>
      </div>
    </div>

    <div class="col-lg-8">
      <div class="w-75 mx-auto">
        <%= link_to '<i class="fas fa-arrow-left mr-3"></i>Back to tasks'.html_safe, tasks_path, class: 'text-muted' %>
        <h3 class="mt-5 py-3">New <span class="text-muted">Task</span></h3>
        <div class="field mb-3">
          <%= form.text_area :description, class: 'form-control', placeholder: 'Description' %>
        </div>

        <div class="actions">
          <%= form.submit 'Add task', class: 'btn btn-primary'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to '<i class="fas fa-arrow-left mr-3"></i>Back to projects'.html_safe, projects_path, class: 'text-muted' %>

<h1 class="text-center mt-4 border-bottom pb-4 mb-5">My <span class="text-muted">Tasks</span></h1>

<div class="text-center">
  <div>
    <%= link_to '<i class="fas fa-plus text-primary"></i>'.html_safe, new_task_path, class: 'border py-2 px-3 rounded text-muted' %>
  </div>
  <div class="mt-4">
    <%= link_to 'New Task', new_task_path, class: 'text-muted' %>
  </div>
</div>

<div class="bg-light mt-4 mx-auto w-50 rounded py-4 px-5">
<% @tasks.each do |task| %>
  <span class="d-block border-bottom py-3 pl-2">
    <i class="fas fa-arrow-circle-right mr-3 text-muted"></i>
    <%= link_to task.description, task, class: 'font-weight-bold text-muted' %>
  </span>
<% end %>
</div>

app/views/tasks/new.html.erb
<div class="mt-4">
  <%= render 'form', task: @task %>
<div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '<i class="fas fa-arrow-left mr-3"></i>Back to tasks'.html_safe, tasks_path, class: 'text-muted' %>

<div class="row">
  <div class="col-lg-4">
    <h3 class="mt-5">
      Task: <br>
      <span class="text-muted">
        <%= @task.description %>
      </span>
    </h3>
    <h5 class="my-5">
      Project: <br>
      <span class="text-muted">
        <%= @task.project.title %>
      </span>
    </h5>

    <%= link_to '<i class="fas fa-pencil-alt mr-2"></i>Edit task'.html_safe, edit_task_path(@task), class: 'mr-4 font-weight-bold'%>
  </div>

  <div class="col-lg-8">
    <div class="bg-light py-4 px-5">
      <h4 class="text-muted border-bottom py-4 mb-4 text-center">Comments for this task</h4>
      <div class="text-center pt-3">
        <%= link_to '<i class="fas fa-plus mr-2"></i>New comment'.html_safe, new_comment_path, class: 'border py-2 px-3 rounded' %>
      </div>
      <div class="mt-5 w-75 mx-auto">
        <% @comments.each do |comment| %>
          <span class="d-block">
            > <%= link_to comment.body, comment %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>